spring:
  profiles: peer1
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: true
    number-of-replication-retries: 0
    response-cache-auto-expiration-in-seconds: 500
    remote-region-registry-fetch-interval: 15
    max-time-for-replication: 600000
    disable-delta: true
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 45

---
spring:
  profiles: peer2
server:
  port: 8771

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: true
    number-of-replication-retries: 0
    response-cache-auto-expiration-in-seconds: 500
    remote-region-registry-fetch-interval: 15
    max-time-for-replication: 600000
  instance:
    hostname: localhost
