spring:
  profiles: local

foresee-services: http://portal-local.answers.com/foresee-services

eureka:
  client:
    registerWithEureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    disable-delta: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    enableSelfPreservation: false
    instance-info-replication-interval-seconds: 30
    lease-renewal-interval-in-seconds: 15
    home-page-url-path: /
    health-check-url-path: /status
    status-page-url-path: /status

---

spring:
  profiles: dev

foresee-services: http://acs-dev-portal01.aa1.afcv.net/foresee-services

eureka:
  client:
    registerWithEureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    disable-delta: true
    serviceUrl:
      defaultZone: http://vocdiscovery-env.elasticbeanstalk.com/eureka/
  instance:
    enableSelfPreservation: false
    instance-info-replication-interval-seconds: 30
    lease-renewal-interval-in-seconds: 15
    home-page-url-path: /
    health-check-url-path: /status
    status-page-url-path: /status

---

zuul:
  routes:
    fss:
      path: /fss/**
      serviceId: foresee-services
      stripPrefix: true

    index:
      path: /index.jsp
      serviceId: foresee-services
      stripPrefix: false

    notifications:
      path: /notifications/**
      url: ${foresee-services}
      stripPrefix: false

    users:
      path: /clients/**/users/**
      url: ${foresee-services}
      stripPrefix: false

    channels:
      path: /clients/**/channels/**
      url: ${foresee-services}
      stripPrefix: false

    measures:
      path: /clients/**/measures/**
      url: ${foresee-services}
      stripPrefix: false

    combined_scores:
      path: /clients/**/combinedscores/**
      url: ${foresee-services}
      stripPrefix: false

    dashboards:
      path: /clients/**/dashboards/**
      url: ${foresee-services}
      stripPrefix: false

    shares:
      path: /shares/**
      serviceId: foresee-services
      stripPrefix: false

    custom_reports:
      path: /clients/**/customreports/**
      url: ${foresee-services}
      stripPrefix: false

    topics_summary:
      path: /clients/**/projects/**/topics/summary
      url: ${foresee-services}
      stripPrefix: false

    topic_summary:
      path: /clients/**/projects/**/topics/**/summary
      serviceId: acs-reporting
      stripPrefix: false

    project_metrics:
      path: /clients/**/projects/**/metrics
      serviceId: acs-reporting
      stripPrefix: false

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  eureka:
    enabled: true
health:
  hystrix:
    enabled: true
